// Copy this text, paste to https://dbdiagram.io/d
// Or, https://databasediagram.com/app
// Or, view in VSCode with extension: "DBML Live Preview"

Table Role {
    name VARCHAR(64) [primary key]
    }

Table User {
    name VARCHAR(128) 
    notes TEXT 
    id VARCHAR(64) [primary key]
    username VARCHAR(128) 
    email VARCHAR(128) 
    password_hash VARCHAR(200) 
    }

Table UserRole {
    user_id VARCHAR(64) [primary key]
    notes TEXT 
    role_name VARCHAR(64) 
    }



// Relationships
    Ref: UserRole.(role_name) < Role.(name)
    Ref: UserRole.(user_id) < User.(id)
